import type { ComponentType } from "react";
import {
  Amphora,
  Anchor,
  Anvil,
  Barrel,
  Beer,
  Bird,
  Book,
  Bug,
  Building2,
  Castle,
  Cat,
  Church,
  CircleAlert,
  CircleDashed,
  CircleQuestionMark,
  Dog,
  Egg,
  Fish,
  Flame,
  Gem,
  Ham,
  Heart,
  Hotel,
  Landmark,
  Locate,
  Milk,
  Mountain,
  MountainSnow,
  Panda,
  PawPrint,
  Pickaxe,
  Pyramid,
  Rabbit,
  Rat,
  School,
  Scroll,
  ShieldHalf,
  Shrimp,
  Shrub,
  Skull,
  Snail,
  Sprout,
  Squirrel,
  Star,
  Store,
  Swords,
  Telescope,
  Tent,
  TreeDeciduous,
  TreePalm,
  TreePine,
  Turtle,
  University,
  Warehouse,
  Waves,
  Wheat,
  Worm,
} from "lucide-react";

export type Stamp = {
  name: string;
  icon: ComponentType<{ size?: number }>;
};
export type StampGroup = Stamp[];
export type Stamps = {
  [key in keyof typeof STAMPS]: StampGroup;
} & {
  [key: string]: StampGroup;
};

export const STAMPS: { [key: string]: Stamp[] } = {
  noStamp: [{ name: "No Stamp", icon: CircleDashed }],
  natural: [
    { name: "Flame", icon: Flame },
    { name: "Mountain", icon: Mountain },
    { name: "MountainSnow", icon: MountainSnow },
    { name: "Shrub", icon: Shrub },
    { name: "Sprout", icon: Sprout },
    { name: "TreePine", icon: TreePine },
    { name: "TreePalm", icon: TreePalm },
    { name: "TreeDeciduous", icon: TreeDeciduous },
    { name: "Waves", icon: Waves },
    { name: "Wheat", icon: Wheat },
  ],
  structures: [
    { name: "Castle", icon: Castle },
    { name: "Church", icon: Church },
    { name: "City", icon: Building2 },
    { name: "Hotel", icon: Hotel },
    { name: "Landmark", icon: Landmark },
    { name: "Pyramid", icon: Pyramid },
    { name: "School", icon: School },
    { name: "Store", icon: Store },
    { name: "Tent", icon: Tent },
    { name: "University", icon: University },
    { name: "Warehouse", icon: Warehouse },
  ],
  critters: [
    { name: "Bird", icon: Bird },
    { name: "Bug", icon: Bug },
    { name: "Cat", icon: Cat },
    { name: "Dog", icon: Dog },
    { name: "Egg", icon: Egg },
    { name: "Fish", icon: Fish },
    { name: "Panda", icon: Panda },
    { name: "Paw", icon: PawPrint },
    { name: "Rabbit", icon: Rabbit },
    { name: "Rat", icon: Rat },
    { name: "Shrimp", icon: Shrimp },
    { name: "Snail", icon: Snail },
    { name: "Squirrel", icon: Squirrel },
    { name: "Turtle", icon: Turtle },
    { name: "Worm", icon: Worm },
  ],
  objects: [
    { name: "Amphora", icon: Amphora },
    { name: "Anchor", icon: Anchor },
    { name: "Anvil", icon: Anvil },
    { name: "Barrel", icon: Barrel },
    { name: "Beer", icon: Beer },
    { name: "Book", icon: Book },
    { name: "Gem", icon: Gem },
    { name: "Ham", icon: Ham },
    { name: "Milk", icon: Milk },
    { name: "Pickaxe", icon: Pickaxe },
    { name: "Scroll", icon: Scroll },
    { name: "Skull", icon: Skull },
    { name: "ShieldHalf", icon: ShieldHalf },
    { name: "Swords", icon: Swords },
    { name: "Telescope", icon: Telescope },
  ],
  symbols: [
    { name: "Star", icon: Star },
    { name: "Heart", icon: Heart },
    { name: "Alert", icon: CircleAlert },
    { name: "CircleQuestionMark", icon: CircleQuestionMark },
    { name: "Locate", icon: Locate },
  ],
};

export const STAMP_ICONS = [
  ...STAMPS.noStamp,
  ...STAMPS.natural,
  ...STAMPS.structures,
  ...STAMPS.critters,
  ...STAMPS.objects,
  ...STAMPS.symbols,
];

export const STAMP_GROUP_ORDER = [
  "noStamp",
  "natural",
  "structures",
  "critters",
  "objects",
  "symbols",
];
